### ISSUE TITLE
[BUG] -Radarr -  is not ready, sleeping until valid response

### ISSUE THREAD

**Issue by almulder** [RandomNinjaAtk/arr-scripts#283]
**Application**
Radarr 

**Host platform**
Unraid

**Script**
2024-07-09 16:49:55 :: InvalidMoviesAutoCleaner :: 1.2 ::  is not ready, sleeping until valid response...
2024-07-09 16:49:55 :: AutoExtras :: 1.5 ::  is not ready, sleeping until valid response...
2024-07-09 16:49:55 :: Recyclarr :: 1.8 ::  is not ready, sleeping until valid response...
2024-07-09 16:49:55 :: AutoConfig :: 1.9 ::  is not ready, sleeping until valid response...
2024-07-09 10:49:55 :: QueueCleaner :: 1.9 ::  is not ready, sleeping until valid response...

Everything has been working great for many months, then a few months ago it stopped getting trailers and summer being here, I was very busy. I finally had time to look into the issue and not sure what is causing this as everything had been working and no changes have been made other than the dockers updated. no settings have changed inside dockers or within unraid.

I uninstalled the scripts and started from scratch and the issue still happens. what can I look at next?

**Comment by almulder** [comment]
Looking in logs, I am seeing this message when restarting:


/config/extended/functions: line 21: xq: command not found
/config/extended/functions: line 21: xq: command not found
/config/extended/functions: line 21: xq: command not found
/config/extended/functions: line 21: xq: command not found
/config/extended/functions: line 27: xq: command not found
/config/extended/functions: line 21: xq: command not found
/config/extended/functions: line 27: xq: command not found
/config/extended/functions: line 27: xq: command not found
/config/extended/functions: line 27: xq: command not found
/config/extended/functions: line 28: xq: command not found
/config/extended/functions: line 28: xq: command not found
/config/extended/functions: line 27: xq: command not found
/config/extended/functions: line 29: xq: command not found
/config/extended/functions: line 28: xq: command not found
/config/extended/functions: line 28: xq: command not found
/config/extended/functions: line 29: xq: command not found
/config/extended/functions: line 29: xq: command not found
/config/extended/functions: line 28: xq: command not found
/config/extended/functions: line 29: xq: command not found
/config/extended/functions: line 29: xq: command not found

**Comment by almulder** [comment]
digging deeper it looks to be an issue here:
[custom-init] Files found, executing
[custom-init] scripts_init.bash: executing...
************ install packages ************
fetch http://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
OK: 686 MiB in 220 packages
************ install python packages ************
*********SMA WORKAROUND ************
DEPRECATION: Loading egg at /usr/lib/python3.12/site-packages/qtfaststart-1.8-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: requests in /usr/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: idna in /usr/lib/python3.12/site-packages (3.7)
Requirement already satisfied: requests-cache in /usr/lib/python3.12/site-packages (1.2.1)
Requirement already satisfied: babelfish in /usr/lib/python3.12/site-packages (0.6.1)
Requirement already satisfied: tmdbsimple in /usr/lib/python3.12/site-packages (2.9.1)
Requirement already satisfied: mutagen in /usr/lib/python3.12/site-packages (1.47.0)
Requirement already satisfied: guessit in /usr/lib/python3.12/site-packages (3.8.0)
Requirement already satisfied: subliminal in /usr/lib/python3.12/site-packages (2.2.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3.12/site-packages (2.9.0.post0)
Requirement already satisfied: stevedore in /usr/lib/python3.12/site-packages (5.2.0)
Requirement already satisfied: cleanit in /usr/lib/python3.12/site-packages (0.4.8)
Requirement already satisfied: plexapi in /usr/lib/python3.12/site-packages (4.15.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.12/site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.12/site-packages (from requests) (2024.7.4)
Requirement already satisfied: attrs>=21.2 in /usr/lib/python3.12/site-packages (from requests-cache) (23.2.0)
Requirement already satisfied: cattrs>=22.2 in /usr/lib/python3.12/site-packages (from requests-cache) (23.2.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/lib/python3.12/site-packages (from requests-cache) (4.2.2)
Requirement already satisfied: url-normalize>=1.4 in /usr/lib/python3.12/site-packages (from requests-cache) (1.4.3)
Requirement already satisfied: rebulk>=3.2.0 in /usr/lib/python3.12/site-packages (from guessit) (3.2.0)
Requirement already satisfied: beautifulsoup4>=4.4.0 in /usr/lib/python3.12/site-packages (from subliminal) (4.12.3)
Requirement already satisfied: chardet>=5.0 in /usr/lib/python3.12/site-packages (from subliminal) (5.2.0)
Requirement already satisfied: click>=8.0 in /usr/lib/python3.12/site-packages (from subliminal) (8.1.7)
Requirement already satisfied: click-option-group>=0.5.6 in /usr/lib/python3.12/site-packages (from subliminal) (0.5.6)
Requirement already satisfied: dogpile.cache>=1.0 in /usr/lib/python3.12/site-packages (from subliminal) (1.3.3)
Requirement already satisfied: enzyme>=0.5.0 in /usr/lib/python3.12/site-packages (from subliminal) (0.5.2)
Requirement already satisfied: pysubs2>=1.7 in /usr/lib/python3.12/site-packages (from subliminal) (1.7.2)
Requirement already satisfied: rarfile>=2.7 in /usr/lib/python3.12/site-packages (from subliminal) (4.2)
Requirement already satisfied: srt>=3.5 in /usr/lib/python3.12/site-packages (from subliminal) (3.5.3)
Requirement already satisfied: tomli>=2 in /usr/lib/python3.12/site-packages (from subliminal) (2.0.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.12/site-packages (from python-dateutil) (1.16.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/lib/python3.12/site-packages (from stevedore) (6.0.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /usr/lib/python3.12/site-packages (from cleanit) (1.4.4)
Requirement already satisfied: jsonschema<5.0.0,>=4.17.3 in /usr/lib/python3.12/site-packages (from cleanit) (4.22.0)
Requirement already satisfied: pysrt<2.0.0,>=1.1.2 in /usr/lib/python3.12/site-packages (from cleanit) (1.1.2)
Requirement already satisfied: pyyaml<7.0,>=6.0 in /usr/lib/python3.12/site-packages (from cleanit) (6.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.12/site-packages (from beautifulsoup4>=4.4.0->subliminal) (2.5)
Requirement already satisfied: decorator>=4.0.0 in /usr/lib/python3.12/site-packages (from dogpile.cache>=1.0->subliminal) (5.1.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/lib/python3.12/site-packages (from jsonschema<5.0.0,>=4.17.3->cleanit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/lib/python3.12/site-packages (from jsonschema<5.0.0,>=4.17.3->cleanit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/lib/python3.12/site-packages (from jsonschema<5.0.0,>=4.17.3->cleanit) (0.18.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 24.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip
************ setup directory ************
************ download repo ************
Cloning into '/usr/local/sma'...
************ create logging file ************
************ install pip dependencies ************
DEPRECATION: Loading egg at /usr/lib/python3.12/site-packages/qtfaststart-1.8-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: pip==24.1 in /usr/lib/python3.12/site-packages (24.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 24.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip

**Comment by RandomNinjaAtk** [comment]
Hmmm, thanks for the report, I'll look into it when I have some time. However, please double check that you followed the installation instructions correctly because that is typically the cause....

**Comment by tikibozo** [comment]
+1 on this - I'm seeing the same with no installation changes.

**Comment by RandomNinjaAtk** [comment]
Thx, I can confirm that I'm seeing the same issue. I'll see if I can get it resolved tonight.

**Comment by RandomNinjaAtk** [comment]
This should now be resolved, please confirm. Restart your container to get the fix...

**Comment by tikibozo** [comment]
Extras is still running, but looking good from here. Thanks for the quick fix!

**Comment by kerta1n** [comment]
I am still getting the Audio 2.48, Autoconfig 3.2, and QueueCleaner 1.9 errors, but I updated my `extended.conf` with all of the new parameters and have restarted about 5 times now, giving 4-5 min in between.

**Comment by kerta1n** [comment]
Looking over #279, it seems the service that isn't starting is blank. 
![image](https://github.com/user-attachments/assets/32ed152f-5f24-4071-a4fa-c3fcd08e33f6)

**Comment by kerta1n** [comment]
I am also getting a JQ error and a python error about module `telegram` missing, even though I didn't configure it.

```
2024-10-25 20:09:10 :: TidalVideoDownloader :: 2.1 :: Sleeping (infinity)
2024-10-25 20:09:10 :: UnmappedFilesCleaner :: 1.4 :: Script starting...
2024-10-25 20:09:10 :: AutoArtistAdder :: 2.4 :: Script starting...
2024-10-25 20:09:10 :: UnmappedFilesCleaner :: 1.4 :: Script is not enabled, enable by setting enableUnmappedFilesCleaner to "true" by modifying the "/config/extended.conf" config file...
2024-10-25 20:09:10 :: Video :: 3.9 :: ERROR: videoPath is not configured via the "/config/extended.conf" config file...
2024-10-25 20:09:10 :: AutoArtistAdder :: 2.4 :: Script is not enabled, enable by setting addDeezerTopArtists. addDeezerTopAlbumArtists, addDeezerTopTrackArtists or addRelatedArtists to "true" by modifying the "/config/extended.conf" config file...
2024-10-25 20:09:10 :: UnmappedFilesCleaner :: 1.4 :: Sleeping (infinity)
2024-10-25 20:09:10 :: Video :: 3.9 :: Updated your "/config/extended.conf" file with the latest options, see: https://github.com/RandomNinjaAtk/arr-scripts/blob/main/lidarr/extended.conf
2024-10-25 20:09:10 :: AutoArtistAdder :: 2.4 :: Sleeping (infinity)
2024-10-25 20:09:10 :: Video :: 3.9 :: Sleeping (infinity)
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
2024-10-25 20:09:10 :: Audio :: 2.48 :: Starting Script....
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
2024-10-26 00:09:10 :: AutoConfig :: 3.2 ::  is not ready, sleeping until valid response...
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
jq: parse error: Invalid numeric literal at line 2, column 0
```

**Comment by kerta1n** [comment]
Fixed by nuking `/custom-services.d` and restarting

**Comment by FrenchToucan** [comment]
This issue popped up for me tonight. 

2025-02-24 22:07:18 :: QueueCleaner :: 2.0 ::  is not ready, sleeping until valid response...
2025-02-25 03:07:18 :: AutoConfig :: 3.2 ::  is not ready, sleeping until valid response...
2025-02-24 22:07:18 :: Audio :: 2.48 ::  is not ready, sleeping until valid response...

**Comment by danutzzzzz** [comment]
Hi.

Im getting this as well, i cant see a full fix for it here..

```
2025-11-19 00:12:24 :: TidalVideoDownloader :: 2.1 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:10 :: Video :: 4.0 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:10 :: QueueCleaner :: 2.0 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:10 :: TidalVideoDownloader :: 2.1 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:11 :: Video :: 4.0 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:11 :: QueueCleaner :: 2.0 ::  is not ready, sleeping until valid response...
2025-11-19 00:21:09 :: TidalVideoDownloader :: 2.1 ::  is not ready, sleeping until valid response...
```
