### ISSUE TITLE
[BUG] - Lidarr - Video download issue : slug not found

### ISSUE THREAD

**Issue by TheLazyGeekGuy** [RandomNinjaAtk/arr-scripts#371]
**Application**
Lidarr

**Host platform**
Docker

**Script**
video downloader

**Script Version**
latest scrpt version

**Describe the bug**
The video downloader don't find the artists on imvdb, even when it's not down
For exemple kavinsky, is not found https://imvdb.com/n/kavinsky

**Logs/Screenshots**

2025-05-17 16:32:05 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: Checking for IMVDB Slug
2025-05-17 16:32:05 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: IMVDB :: ERROR :: No IMVDB artist link found, skipping...
2025-05-17 16:32:05 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: IMVDB :: Logging missing IMVDB artist in folder: /config/extended/logs/video/imvdb-link-missing
2025-05-17 16:32:05 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: Music Videos previously downloaded, skipping...

**Comment by steve1977** [comment]
Linked was missing from MBZ. I added it and it should work now. You can easily add missing IMVDB links to MBZ yourself. That's required to make this script work.

**Comment by TheLazyGeekGuy** [comment]
Thank you for the feedback.

MBZ is for musicbrainz i guess ?

**Comment by TheLazyGeekGuy** [comment]
> 2025-05-18 18:59:38 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: Checking for IMVDB Slug
> 2025-05-18 18:59:38 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: IMVDB :: ERROR :: No IMVDB artist link found, skipping...
> 2025-05-18 18:59:38 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: IMVDB :: Logging missing IMVDB artist in folder: /config/extended/logs/video/imvdb-link-missing
> 2025-05-18 18:59:38 :: Video :: 4.0 :: 60/2459 :: Kavinsky :: Music Videos previously downloaded, skipping...

Stopped and restart, then clean and rebuild but still the same error.

**Comment by steve1977** [comment]
You may need to wait some days for the update to be reflected.

You will see a full lists of artists missing the link in musicbrainz under /config/extended/logs/video/imvdb-link-missing. Feel free to add more.

**Comment by TheLazyGeekGuy** [comment]
> 2025-05-24 14:24:22 :: Video :: 4.0 :: 60/2463 :: Kavinsky :: Checking for IMVDB Slug
> 2025-05-24 14:24:22 :: Video :: 4.0 :: 60/2463 :: Kavinsky :: IMVDB :: Slug :: kavinsky

It took time to refresh into my lidar instance.
IMVDB link show up, but no download so far ... :-/

**Comment by jaycedk** [comment]
I'm also seeing no downloads being done.

2025-05-26 11:18:06 :: Video :: 4.0 :: 502/507 :: Kelly Clarkson :: Checking for IMVDB Slug
2025-05-26 11:18:06 :: Video :: 4.0 :: 502/507 :: Kelly Clarkson :: IMVDB :: Slug :: kelly-clarkson
2025-05-26 11:18:06 :: Video :: 4.0 :: 503/507 :: Scissor Sisters :: Checking for IMVDB Slug
2025-05-26 11:18:06 :: Video :: 4.0 :: 503/507 :: Scissor Sisters :: IMVDB :: Slug :: scissor-sisters
2025-05-26 11:18:06 :: Video :: 4.0 :: 505/507 :: Backstreet Boys :: Checking for IMVDB Slug
2025-05-26 11:18:06 :: Video :: 4.0 :: 505/507 :: Backstreet Boys :: IMVDB :: Slug :: backstreet-boys
2025-05-26 11:18:07 :: Video :: 4.0 :: 507/507 :: Simply Red :: Checking for IMVDB Slug
2025-05-26 11:18:07 :: Video :: 4.0 :: 507/507 :: Simply Red :: IMVDB :: Slug :: simply-red

Here are the video log.

[Video-2025_05_26_11_17_AM.txt](https://github.com/user-attachments/files/20442863/Video-2025_05_26_11_17_AM.txt)

**Comment by TheLazyGeekGuy** [comment]
I think at this time, the issue may be related from a Lidarr issue since few days : due to MusicBrainz change in its DB pattern. 

see that post : [Lidarr API "Internal Server Error" 500](https://github.com/Lidarr/Lidarr/issues/5498#top)
#5498

**Comment by TheLazyGeekGuy** [comment]
I can not download any video nor add new artists in lidarr side ... so wait and see !

**Comment by jaycedk** [comment]
I don't think so since Lidarr has issues with there metadata atm.
That means that you can't add artists to Lidarr.
That has nothing to do with this issue.
![Image](https://github.com/user-attachments/assets/23467405-860c-41b8-a725-d53bc690caae)

**Comment by RandomNinjaAtk** [comment]
Resolved with recent merge, thanks @Podcakero

**Comment by jaycedk** [comment]
@Podcakero @RandomNinjaAtk thank you so much 👍
I'm back rocking and rolling to the music videos 👍
After getting new youtube cookies 😂🤣
